backend:
  name: github
  repo: khubmku/ipldce-study
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "paper1"
    label: "Paper-I Study Material"
    folder: "content/paper1"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Rule / Topic", name: "topic", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
